CREATE DATABASE PIZZARIA;

DROP TABLE IF EXISTS PIZZARIA.CLIENTE;
CREATE TABLE PIZZARIA.CLIENTE (
	COD_CLIENTE 			INT 			NOT NULL 	AUTO_INCREMENT,
	NOME_CLIENTE 			VARCHAR(150) 	NOT NULL,
	RUA 					VARCHAR(150) 	NOT NULL,
	NUMERO 					VARCHAR(20) 	NOT NULL,
	COMPLEMENTO 			VARCHAR(30) 	DEFAULT NULL,
	SENHA 					VARCHAR(100) 	NOT NULL,
	EMAIL 					VARCHAR(100) 	NOT NULL,
	IDF_ATIVO 				VARCHAR(1) 		DEFAULT 'N',
	CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE)
);

DROP TABLE IF EXISTS PIZZARIA.TELEFONE_CLIENTE;
CREATE TABLE PIZZARIA.TELEFONE_CLIENTE (
	COD_CLIENTE 				INT 			NOT NULL,
	TELEFONE 					VARCHAR(11) 	NOT NULL,
	CONSTRAINT PK_TELEFONE_CLIENTE PRIMARY KEY (COD_CLIENTE,TELEFONE),
	CONSTRAINT FK_TELEFONE_CLIENTE_2_CLIENTE 
		FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE)
);

DROP TABLE IF EXISTS PIZZARIA.PIZZA;
CREATE TABLE PIZZARIA.PIZZA (
	COD_PIZZA 				INT 			NOT NULL AUTO_INCREMENT,
	NOME_PIZZA 				VARCHAR(150) 	NOT NULL,
	CONSTRAINT PK_PIZZA PRIMARY KEY (COD_PIZZA)
);

DROP TABLE IF EXISTS PIZZARIA.TAMANHO_PIZZA;
CREATE TABLE PIZZARIA.TAMANHO_PIZZA (
	COD_PIZZA 				INT 				NOT NULL,
	DESC_TAMANHO_PIZZA 		VARCHAR(20) 		NOT NULL,
	PRECO_TAMANHO_PIZZA 	DECIMAL(10,2) 		NOT NULL DEFAULT '0.00',
	PRIMARY KEY (COD_PIZZA,DESC_TAMANHO_PIZZA),
	CONSTRAINT FK_TAMANHO_PIZZA_2_PIZZA 
		FOREIGN KEY (COD_PIZZA) REFERENCES PIZZA (COD_PIZZA)
);

DROP TABLE IF EXISTS PIZZARIA.PEDIDO;
CREATE TABLE PIZZARIA.PEDIDO (
	NUM_PEDIDO 				INT 			NOT NULL AUTO_INCREMENT,
	DATA_PEDIDO 			DATETIME 		NOT NULL,
	ORIGEM_PEDIDO 			VARCHAR(1) 		NOT NULL DEFAULT 'I',
	FORMA_PAGAMENTO 		VARCHAR(1) 		NOT NULL DEFAULT 'D',
	COD_CLIENTE 			INT 			NOT NULL,
	CONSTRAINT PK_PEDIDO PRIMARY KEY (NUM_PEDIDO),
	CONSTRAINT FK_PEDIDO_2_CLIENTE 
		FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE)
);

DROP TABLE IF EXISTS PIZZARIA.CONTEM;
CREATE TABLE PIZZARIA.CONTEM (
	NUM_PEDIDO 			INT 			NOT NULL,
	COD_PIZZA 			INT 			NOT NULL,
	DESC_TAMANHO_PIZZA 	VARCHAR(20) 	NOT NULL,
	QUANTIDADE 			DECIMAL(5,2) 	DEFAULT '1.00',
	PRECO 				DECIMAL(10,2) 	DEFAULT '0.00',
	CONSTRAINT PK_CONTEM PRIMARY KEY (NUM_PEDIDO,COD_PIZZA,DESC_TAMANHO_PIZZA),
	CONSTRAINT FK_CONTEM_2_PEDIDO 
		FOREIGN KEY (NUM_PEDIDO) REFERENCES PEDIDO (NUM_PEDIDO),
	CONSTRAINT FK_CONTEM_2_TAMANHO_PIZZA 
		FOREIGN KEY (COD_PIZZA, DESC_TAMANHO_PIZZA) REFERENCES TAMANHO_PIZZA (COD_PIZZA, DESC_TAMANHO_PIZZA)
);

DROP TABLE IF EXISTS PIZZARIA.INGREDIENTES_PIZZA;
CREATE TABLE IF NOT EXISTS PIZZARIA.INGREDIENTES_PIZZA (
	COD_PIZZA			INT				NOT NULL,
	INGREDIENTE			VARCHAR(255)	NOT NULL,
	CONSTRAINT PK_INGREDIENTES_PIZZA PRIMARY KEY (COD_PIZZA, INGREDIENTE),
	CONSTRAINT FK_INGREDIENTES_PIZZA_2_PIZZA
		FOREIGN KEY (COD_PIZZA) REFERENCES PIZZA (COD_PIZZA)
);





