-- Exercício Slide 19
---------------------
CREATE DATABASE FIPE;

DROP TABLE IF EXISTS FIPE.MARCA;
CREATE TABLE IF NOT EXISTS FIPE.MARCA (
	COD_MARCA			INT				NOT NULL	AUTO_INCREMENT,
    NOM_MARCA			VARCHAR(45)		NOT NULL,
    NOM_MARCA_FIPE		VARCHAR(45)		NOT NULL,
    KEY_MARCA			VARCHAR(45)		NOT NULL,
    ID_MARCA_FIPE		VARCHAR(45)		NOT NULL,
    CONSTRAINT PK_MARCA PRIMARY KEY (COD_MARCA)
);

DROP TABLE IF EXISTS FIPE.TIPO_VEICULO;
CREATE TABLE IF NOT EXISTS FIPE.TIPO_VEICULO (
	COD_TIPO_VEICULO	INT				NOT NULL	AUTO_INCREMENT,
    DSC_TIPO_VEICULO	VARCHAR(45)		NOT NULL,
    CONSTRAINT PK_TIPO_VEICULO PRIMARY KEY (COD_TIPO_VEICULO)
);

DROP TABLE IF EXISTS FIPE.TABELA;
CREATE TABLE IF NOT EXISTS FIPE.TABELA (
	COD_VEICULO			INT				NOT NULL	AUTO_INCREMENT,
    NOM_VEICULO			VARCHAR(45)		NOT NULL,
    NOM_VEICULO_FIPE	VARCHAR(45),
    KEY_VEICULO_FIPE	VARCHAR(45),
    ID_VEICULO_FIPE		VARCHAR(15),
    COD_MARCA			INT				NOT NULL,
    COD_TIPO_VEICULO	INT 			NOT NULL,
    CONSTRAINT PK_MARCA PRIMARY KEY (COD_VEICULO),
    CONSTRAINT FK_TABELA_2_MARCA
		FOREIGN KEY (COD_MARCA) REFERENCES MARCA (COD_MARCA),
	CONSTRAINT FK_TABELA_2_TIPO_VEICULO
		FOREIGN KEY (COD_TIPO_VEICULO) REFERENCES TIPO_VEICULO (COD_TIPO_VEICULO)
);

DROP TABLE IF EXISTS FIPE.MODELO;
CREATE TABLE IF NOT EXISTS FIPE.MODELO (
	SEQ_MODELO			INT				NOT NULL	AUTO_INCREMENT,
    DSC_MODELO			VARCHAR(100)	NOT NULL,
    KEY_MODELO_FIPE		VARCHAR(20)		NOT NULL,
    COD_MODELO_FIPE		VARCHAR(20)		NOT NULL,
    ID_MODELO_FIPE		VARCHAR(20)		NOT NULL,
    COD_VEICULO			INT 			NOT NULL,
    CONSTRAINT PK_MODELO PRIMARY KEY (SEQ_MODELO),
    CONSTRAINT FK_MODELO_2_TABELA
		FOREIGN KEY (COD_VEICULO) REFERENCES TABELA (COD_VEICULO)
);

DROP TABLE IF EXISTS FIPE.VALOR_VEICULO;
CREATE TABLE IF NOT EXISTS FIPE.VALOR_VEICULO (
	SEQ_VALOR_VEICULO		INT				NOT NULL	AUTO_INCREMENT,
    MES_REF_VALOR_VEICULO	INT				NOT NULL,
    ANO_REF_VALOR_VEICULO	YEAR			NOT NULL,
    DSC_VEICULO				VARCHAR(100)	NOT NULL,
    PCO_VALOR_VEICULO		DECIMAL(10,2)	NOT NULL	DEFAULT 0,
    KEY_VEICULO				VARCHAR(20)		NOT NULL,
    ID_VEICULO_FIPE			VARCHAR(20)		NOT NULL,
    COD_VEICULO_FIPE		VARCHAR(20),
    SEQ_MODELO_VEICULO		INT				NOT NULL,
    CONSTRAINT PK_VALOR_VEICULO PRIMARY KEY (SEQ_VALOR_VEICULO),
    CONSTRAINT FK_VALOR_VEICULO_2_MODELO
		FOREIGN KEY (SEQ_MODELO_VEICULO) REFERENCES MODELO (SEQ_MODELO)
);


-- Exercício Slide 20
---------------------
DROP TABLE IF EXISTS FIPE.GRUPO;
CREATE TABLE IF NOT EXISTS FIPE.GRUPO (
	COD_GRUPO		INT 			NOT NULL	AUTO_INCREMENT,
    NOM_GRUPO		VARCHAR(100)	NOT NULL,
    IDF_ATIVO		VARCHAR(1)		DEFAULT 'S',
    CONSTRAINT PK_GRUPO PRIMARY KEY (COD_GRUPO),
    CONSTRAINT CK_GRUPO_ATIVO CHECK (IDF_ATIVO IN ('S','N'))
);

ALTER TABLE FIPE.MARCA MODIFY NOM_MARCA VARCHAR(100) NOT NULL;
ALTER TABLE FIPE.MARCA ADD COD_GRUPO INT NOT NULL;
ALTER TABLE FIPE.MARCA ADD CONSTRAINT FK_MARCA_2_GRUPO 
	FOREIGN KEY (COD_GRUPO) REFERENCES GRUPO (COD_GRUPO);

ALTER TABLE FIPE.TABELA RENAME FIPE.VEICULO;
ALTER TABLE FIPE.VEICULO DROP FOREIGN KEY FK_TABELA_2_MARCA;
ALTER TABLE FIPE.VEICULO DROP FOREIGN KEY FK_TABELA_2_TIPO_VEICULO;
ALTER TABLE FIPE.VEICULO ADD CONSTRAINT FK_VEICULO_2_MARCA
	FOREIGN KEY (COD_MARCA) REFERENCES MARCA (COD_MARCA);
ALTER TABLE FIPE.VEICULO ADD CONSTRAINT FK_VEICULO_2_TIPO_VEICULO
	FOREIGN KEY (COD_TIPO_VEICULO) REFERENCES TIPO_VEICULO (COD_TIPO_VEICULO);


-- Exercício de Inserção
------------------------
INSERT INTO UNICID.CLIENTE (NOME_CLIENTE, RUA, NUMERO, SENHA, EMAIL, IDF_ATIVO)
VALUES ('JOÃO', 'RUA X', '150', '123456789', 'JOAO@CLIENTE.COM.BR', 'S');

INSERT INTO UNICID.CLIENTE (NOME_CLIENTE, RUA, NUMERO, SENHA, EMAIL, IDF_ATIVO)
VALUES ('MARIA', 'RUA X', '160', '123456789', 'MARIA@CLIENTE.COM.BR', 'S');

INSERT INTO UNICID.CLIENTE (NOME_CLIENTE, RUA, NUMERO, SENHA, EMAIL, IDF_ATIVO)
VALUES ('JOSE', 'RUA Y', '255', '987654123', 'JOSE@CLIENTE.COM.BR', 'S');

INSERT INTO UNICID.PIZZA (NOME_PIZZA) VALUES ('A BAIANA');
INSERT INTO UNICID.PIZZA (NOME_PIZZA) VALUES ('ALHO FRITO');
INSERT INTO UNICID.PIZZA (NOME_PIZZA) VALUES ('ALICHE');

INSERT INTO UNICID.TAMANHO_PIZZA (COD_PIZZA, DESC_TAMANHO_PIZZA, PRECO_TAMANHO_PIZZA)
VALUES (1, 'INTEIRA', 52.90);
INSERT INTO UNICID.TAMANHO_PIZZA (COD_PIZZA, DESC_TAMANHO_PIZZA, PRECO_TAMANHO_PIZZA)
VALUES (1, 'BROTO', 34.50);
INSERT INTO UNICID.TAMANHO_PIZZA (COD_PIZZA, DESC_TAMANHO_PIZZA, PRECO_TAMANHO_PIZZA)
VALUES (2, 'INTEIRA', 50.90);
INSERT INTO UNICID.TAMANHO_PIZZA (COD_PIZZA, DESC_TAMANHO_PIZZA, PRECO_TAMANHO_PIZZA)
VALUES (2, 'BROTO', 32.50);
INSERT INTO UNICID.TAMANHO_PIZZA (COD_PIZZA, DESC_TAMANHO_PIZZA, PRECO_TAMANHO_PIZZA)
VALUES (3, 'INTEIRA', 50.90);
INSERT INTO UNICID.TAMANHO_PIZZA (COD_PIZZA, DESC_TAMANHO_PIZZA, PRECO_TAMANHO_PIZZA)
VALUES (3, 'BROTO', 32.50);

INSERT INTO UNICID.PEDIDO (DATA_PEDIDO, ORIGEM_PEDIDO, FORMA_PAGAMENTO, COD_CLIENTE)
VALUES (CURRENT_TIMESTAMP, 'I', 'D', 4);
INSERT INTO UNICID.CONTEM (NUM_PEDIDO, COD_PIZZA, DESC_TAMANHO_PIZZA, QUANTIDADE, PRECO)
VALUES (1, 1, 'INTEIRA', 0.5, 52.90);
INSERT INTO UNICID.CONTEM (NUM_PEDIDO, COD_PIZZA, DESC_TAMANHO_PIZZA, QUANTIDADE, PRECO)
VALUES (1, 2, 'INTEIRA', 0.5, 50.90);

INSERT INTO UNICID.PEDIDO (DATA_PEDIDO, ORIGEM_PEDIDO, FORMA_PAGAMENTO, COD_CLIENTE)
VALUES (CURRENT_TIMESTAMP, 'I', 'D', 3);
INSERT INTO UNICID.CONTEM (NUM_PEDIDO, COD_PIZZA, DESC_TAMANHO_PIZZA, QUANTIDADE, PRECO)
VALUES (2, 3, 'INTEIRA', 1, 50.90);








