-- ##################################################################################
-- EXERCÍCIO

--CLIENTES
----------
-- JOAO


-- MARIA
-- JOSE


--PIZZAS
--------
-- A BAIANA
-- ALHO FRITO
-- ALICHE

-- TAMANHO_PIZZA
--	- A BAIANA 		- INTEIRA E BROTO
--	- ALHO FRITO 	- INTEIRA E BROTO
--	- ALICHE		- INTEIRA E BROTO
    
--PEDIDO
--------
-- JOSE - 0,5 A BAIANA E 0,5 ALHO FRITO
-- MARIA - 1 ALICHE
INSERT INTO PIZZARIA.CLIENTE (NOME_CLIENTE, RUA, NUMERO, SENHA, EMAIL, IDF_ATIVO)
VALUES ('JOAO', 'RUA DAS CARMELITAS', '105B', '123456789', 'JOAO@EU.COM','S');
INSERT INTO PIZZARIA.CLIENTE (NOME_CLIENTE, RUA, NUMERO, SENHA, EMAIL, IDF_ATIVO)
VALUES ('JOSE', 'RUA DAS MANES', '35', '987654321', 'JOSE@EU.COM','S');
INSERT INTO PIZZARIA.CLIENTE (NOME_CLIENTE, RUA, NUMERO, SENHA, EMAIL, IDF_ATIVO)
VALUES ('MARIA', 'AV DA SAUDADE', '333', '123654789', 'MARIA@EU.COM','S');

INSERT INTO PIZZARIA.PIZZA (NOME_PIZZA) VALUES ('A BAIANA');
INSERT INTO PIZZARIA.PIZZA (NOME_PIZZA) VALUES ('ALHO FRITO');
INSERT INTO PIZZARIA.PIZZA (NOME_PIZZA) VALUES ('ALICHE');

INSERT INTO PIZZARIA.TAMANHO_PIZZA (COD_PIZZA, DESC_TAMANHO_PIZZA, PRECO_TAMANHO_PIZZA)
VALUES (1, 'INTEIRA', 52.90);
INSERT INTO PIZZARIA.TAMANHO_PIZZA (COD_PIZZA, DESC_TAMANHO_PIZZA, PRECO_TAMANHO_PIZZA)
VALUES (1, 'BROTO', 34.50);
INSERT INTO PIZZARIA.TAMANHO_PIZZA (COD_PIZZA, DESC_TAMANHO_PIZZA, PRECO_TAMANHO_PIZZA)
VALUES (2, 'INTEIRA', 50.90);
INSERT INTO PIZZARIA.TAMANHO_PIZZA (COD_PIZZA, DESC_TAMANHO_PIZZA, PRECO_TAMANHO_PIZZA)
VALUES (2, 'BROTO', 32.50);
INSERT INTO PIZZARIA.TAMANHO_PIZZA (COD_PIZZA, DESC_TAMANHO_PIZZA, PRECO_TAMANHO_PIZZA)
VALUES (3, 'INTEIRA', 50.90);
INSERT INTO PIZZARIA.TAMANHO_PIZZA (COD_PIZZA, DESC_TAMANHO_PIZZA, PRECO_TAMANHO_PIZZA)
VALUES (3, 'BROTO', 32.50);

INSERT INTO PIZZARIA.PEDIDO (DATA_PEDIDO, ORIGEM_PEDIDO, FORMA_PAGAMENTO, COD_CLIENTE)
VALUES (CURRENT_TIMESTAMP, 'I', 'D', 2);
INSERT INTO PIZZARIA.CONTEM (NUM_PEDIDO, COD_PIZZA, DESC_TAMANHO_PIZZA, QUANTIDADE, PRECO)
VALUES (1, 1, 'INTEIRA', 0.5, 26.45);
INSERT INTO PIZZARIA.CONTEM (NUM_PEDIDO, COD_PIZZA, DESC_TAMANHO_PIZZA, QUANTIDADE, PRECO)
VALUES (1, 2, 'INTEIRA', 0.5, 25.45);

INSERT INTO PIZZARIA.PEDIDO (DATA_PEDIDO, ORIGEM_PEDIDO, FORMA_PAGAMENTO, COD_CLIENTE)
VALUES (CURRENT_TIMESTAMP, 'I', 'D', 3);
INSERT INTO PIZZARIA.CONTEM (NUM_PEDIDO, COD_PIZZA, DESC_TAMANHO_PIZZA, QUANTIDADE, PRECO)
VALUES (2, 3, 'INTEIRA', 1, 50.90);


